export const REGISTER_USER = "REGISTER_USER";
export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const LOGIN = "LOGIN";
export const LOGIN_INIT = "LOGIN_INIT";

export const LOGOUT = "LOGOUT";
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_START = "USER_SIGNUP_START";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const USER_SIGNUP_INIT = "USER_SIGNUP_INIT";
