const Routes = [
    {
      name: "signup",
      path: "/signup",
      compPath: "Auth/SignUp/SignUp",
      component: "Register",
      authRoute: false,
      isExact: false,
    },
    {
      name: "signin",
      path: "/signin",
      compPath: "Auth/SignIn/SignIn",
      component: "Login",
      authRoute: false,
      isExact: false,
    },
    {
      name: "dashboard",
      path: "/dashboard",
      compPath: "Dashboard/Dashboard",
      component: "Dashboard",
      authRoute: true,
      isExact: true,
    },
    {
      name: "home",
      path: "/",
      compPath: "Home/Home",
      component: "Home",
      authRoute: false,
      isExact: true,
    },
    {
      name: "books",
      path: "/dashboard/books",
      compPath: "Book/BookListComp/BookListComp",
      component: "BookListComp",
      authRoute: true,
      isExact: true,
    },
    {
      name: "order",
      path: "/order",
      compPath: "Order/Order",
      component: "Order",
      authRoute: false,
      isExact: false,
    },
    
    {
      name: "createbook",
      path: "/dashboard/books/create",
      compPath: "BookCreate/BookCreate",
      component: "BookCreate",
      authRoute: true,
      isExact: false,
    },
    
    {
      name: "logout",
      path: "/logout",
      compPath: "Auth/Logout/Logout",
      component: "Logout",
      authRoute: true,
      isExact: false,
    },
    {
      name: "booklist",
      path: "/dashboard/booklist",
      compPath: "BookList/BookList",
      component: "Booklist",
      authRoute: true,
      isExact: false,
    },
    {
      name: "my-orders",
      path: "/dashboard/my-orders",
      compPath: "MyOrders/MyOrders",
      component: "MyOrders",
      authRoute: true,
      isExact: true,
    },
    {
      name: "bookEdit",
      path: "/dashboard/books/edit/:id",
      compPath: "Book/BookEdit/BookEdit",
      component: "BookEdit",
      authRoute: true,
      isExact: false,
    },
  ];
  
  export default Routes;
  